/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    APopco: typeof import('@arco-design/web-vue')['Popco']
    APopcon: typeof import('@arco-design/web-vue')['Popcon']
    APopconform: typeof import('@arco-design/web-vue')['Popconform']
    AText: typeof import('@arco-design/web-vue')['Text']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
